# Generated by Django 2.0.6 on 2018-06-16 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mode', models.IntegerField(choices=[(0, 'setup'), (1, 'run'), (2, 'stop')], default='setup')),
                ('net_value', models.FloatField(blank=True, null=True)),
                ('cash_to_trade', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='date of quote')),
                ('price', models.FloatField(verbose_name='price of the symbol at the time')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteName',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('share', models.FloatField(verbose_name='budget rate in the account')),
                ('algorithm', models.IntegerField(choices=[(0, 'fill'), (1, 'ahnyung'), (2, 'empty')])),
                ('stance', models.IntegerField(choices=[(0, 'conservative'), (1, 'moderate'), (2, 'aggressive')])),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('last_count', models.FloatField(blank=True, null=True)),
                ('last_sell_price', models.FloatField(blank=True, null=True)),
                ('last_buy_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField(verbose_name='trade date')),
                ('price', models.FloatField()),
                ('type', models.IntegerField(choices=[(0, 'buy'), (1, 'sell'), (2, 'sell_fail'), (3, 'sell_fail')])),
            ],
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account_id', 'symbol', '-date'], name='stock_trade_account_d9ac33_idx'),
        ),
        migrations.AddField(
            model_name='stock',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Account'),
        ),
        migrations.AddField(
            model_name='quote',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.QuoteName'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('account', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['name', '-date'], name='stock_quote_name_id_89d03f_idx'),
        ),
    ]
