# Generated by Django 2.0.6 on 2018-06-16 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=10)),
                ('net_value', models.FloatField(null=True)),
                ('cash_to_trade', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField(verbose_name='date of quote')),
                ('price', models.FloatField(verbose_name='price of the symbol at the time')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('share', models.FloatField(verbose_name='budget rate in the account')),
                ('algorithm', models.IntegerField(choices=[(0, 'fill'), (1, 'ahnyung'), (2, 'empty')])),
                ('stance', models.IntegerField(choices=[(0, 'conservative'), (1, 'moderate'), (2, 'aggressive')])),
                ('count', models.IntegerField(null=True)),
                ('last_value', models.FloatField(null=True)),
                ('last_count', models.FloatField(null=True)),
                ('last_sell_price', models.FloatField(null=True)),
                ('last_buy_price', models.FloatField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField(verbose_name='trade date')),
                ('price', models.FloatField()),
                ('type', models.IntegerField(choices=[(0, 'buy'), (1, 'sell')])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('account', 'symbol')},
        ),
    ]
