# Generated by Django 2.0.6 on 2018-06-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mode', models.IntegerField(choices=[(0, 'setup'), (1, 'run'), (2, 'stop')], default='setup')),
                ('net_value', models.FloatField(blank=True, null=True)),
                ('cash_to_trade', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('net_value', models.FloatField()),
                ('cash_to_trade', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Account')),
            ],
        ),
        migrations.CreateModel(
            name='OrderID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField(verbose_name='date of quote')),
                ('price', models.FloatField(verbose_name='price of the symbol at the time')),
            ],
        ),
        migrations.CreateModel(
            name='SimQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField(verbose_name='date of quote')),
                ('price', models.FloatField(verbose_name='price of the symbol at the time')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('share', models.FloatField(verbose_name='budget rate in the account')),
                ('algorithm', models.IntegerField(choices=[(0, 'fill'), (1, 'ahnyung'), (2, 'empty')])),
                ('stance', models.IntegerField(choices=[(0, 'conservative'), (1, 'moderate'), (2, 'aggressive')])),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('last_count', models.FloatField(blank=True, null=True)),
                ('last_sell_price', models.FloatField(blank=True, null=True)),
                ('last_buy_price', models.FloatField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField(verbose_name='trade date')),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('action', models.IntegerField(choices=[(0, 'buy'), (1, 'sell'), (2, 'buy_fail'), (3, 'sell_fail')])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together={('account_id', 'symbol', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='simquote',
            unique_together={('symbol', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('symbol', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('account', 'symbol')},
        ),
        migrations.AlterUniqueTogether(
            name='dayreport',
            unique_together={('date', 'account')},
        ),
    ]
