# Generated by Django 2.0.6 on 2018-06-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cash_to_trade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mode',
            field=models.CharField(blank=True, default='setup', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='net_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_buy_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_sell_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
