# Generated by Django 2.0.6 on 2018-06-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_orderindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='type',
            field=models.IntegerField(choices=[(0, 'buy'), (1, 'sell'), (2, 'sell_fail'), (3, 'sell_fail')]),
        ),
    ]
